name: flutter_movie_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http:
  percent_indicator:
  intl:
  fancy_shimmer_image:
  flutter_spinkit:
  carousel_slider:
  flutter_icons:
  youtube_player_flutter:
  expand_widget:
  provider:
  url_launcher:
  shimmer:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/